name: Upload notebooks to TileDB Cloud
description: Upload notebooks to TileDB Cloud
inputs:
  notebooks_local:
    description: >-
      The path(s) to the notebook(s) to upload. Must have extension ".ipynb".
      Separate multiple paths with whitespace. The path(s) cannot include spaces
    required: true
  notebooks_remote:
    description: >-
      The full URI(s) on TileDB Cloud (no file extension), eg
      'tiledb://namespace/s3://path/notebook'. Separate multiple URIs with
      whitespace
    required: true
  TILEDB_CLOUD_TOKEN:
    description: 'API token for TileDB Cloud account (scope: `array:admin`)'
    required: true
  TILEDB_CLOUD_STORAGE_CREDENTIAL_NAME:
   description: >-
     Storage credentials to use on TileDB Cloud. If not specified, the API token
     must have scope `*` in order to query your user profile to obtain the name
     of your default cloud credentials
   required: false
runs:
  using: "composite"
  steps:
    - name: Install tiledb-cloud package in virtual env
      run: |
        python3 -m venv "$RUNNER_TEMP/pyenv"
        "$RUNNER_TEMP/pyenv/bin/pip" install tiledb "tiledb-cloud>=0.10.1"
        "$RUNNER_TEMP/pyenv/bin/pip" list
      shell: bash
    - name: Upload notebooks
      env:
        TILEDB_CLOUD_TOKEN: ${{ inputs.TILEDB_CLOUD_TOKEN }}
      run: |
        "$RUNNER_TEMP/pyenv/bin/python3" \
          "${{ github.action_path }}/upload-notebooks.py" \
          --notebooks-local ${{ inputs.notebooks_local }} \
          --notebooks-remote ${{ inputs.notebooks_remote }} \
          --tiledb-cloud-storage-credential-name ${{ inputs.TILEDB_CLOUD_STORAGE_CREDENTIAL_NAME }}
      shell: bash
