name: Test action open-issue
on:
  push:
    # Only create test Issue on branches, not post-merge
    branches-ignore:
      - main
    paths:
      - '.github/workflows/open-issue.yml'
      - 'open-issue/**'
  workflow_dispatch:
jobs:
  open-issue-script:
    permissions:
      issues: write
    runs-on: ${{ matrix.os }}
    name: Test open-issue.sh (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Test script
      env:
        GH_TOKEN: ${{ github.token }}
        TZ: "America/New_York"
        OPEN_ISSUE_ACTION_NAME: Nightly build
        OPEN_ISSUE_ACTION_LABEL: wontfix,bug
        OPEN_ISSUE_ACTION_ASSIGNEE: jdblischak
      run: cd open-issue && bash open-issue.sh
      shell: bash
  open-issue-action:
    permissions:
      issues: write
    needs: [open-issue-script]
    runs-on: ${{ matrix.os }}
    name: Test open-issue action (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Test action
      uses: ./open-issue
      with:
        name: Nightly build
        label: wontfix,bug
        assignee: jdblischak
  close-issue:
    permissions:
      issues: write
    needs: [open-issue-script, open-issue-action]
    runs-on: ubuntu-latest
    if: always()
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Close test Issue
      run: |
        existing=$(gh issue list \
          --label wontfix \
          --limit 1 \
          --jq '.[].number' \
          --json "number" \
          --state "open")

        gh issue close "$existing"
      shell: bash
